@startuml

title
Cars - Class diagram
end title

skinparam class {
	BackgroundColor STRATEGY
	ArrowColor DarkSlateGray
	BorderColor DarkSlateGray
}

skinparam linetype ortho

class Car {
    + id : int
    + brand : String
    + model : String
}

class Owner {
    + id : int
    + name : String
}

class Dealership {
    + id : int
    + name : String
    + address : String
}

Car "0..*"  ---*  "0..1" Owner      : "< owns"
Car "0..*"  ---*  "0..*" Dealership : "< sells"

@enduml