@startuml

title
Cars - Class diagram
end title

skinparam class {
	BackgroundColor STRATEGY
	ArrowColor DarkSlateGray
	BorderColor DarkSlateGray
}

skinparam linetype ortho

class Voiture {
    + id : int
    + brand : String
    + model : String
    + mpg : double
    getLitersPer100Kilometers() : String
}

class Roue {
}

class Personne {
    + adresse
    + ...
}

Voiture          o--- "4"     Roue
Voiture "0..n  " ---o "0..1"  Personne : "< est propriétraire"

package cities {
    class Country {
        + language : Language
    }
    class Region {
    }
    enum Language {
        FR
        EN
    }
    Country *-- Region
}

package auth {
    class Utilisateur {
        + username
        + password
    }
    class Role {
    }
    Utilisateur "*" o-- "*" Role
    Personne ---|> Utilisateur
}

@enduml