@startuml

title
Cars - Entity Relationship diagram
end title

skinparam class {
	BackgroundColor STRATEGY
	ArrowColor DarkSlateGray
	BorderColor DarkSlateGray
}

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "voitures" {
  *id : SERIAL
  --
  *brand : VARCHAR(200)
  *model : VARCHAR(200)
  *mpg : DOUBLE
}

entity "voitures_publications" {
  *id_car : INTEGER <<FOREIGN KEY>>
  *id_dealership : INTEGER <<FOREIGN KEY>>
}

entity "publication" {
  *id : INTEGER <<generated>>
  --
  *name : VARCHAR(200)
  date : DATE
  country : CHAR(2)
}

'cars "*" }o--o{ "*" cars_dealearships
'cars_dealearships "*" }o--o{ "*" dealearships

voitures               "0..*"  ---  "1"     voitures_publications
voitures_publications  "1 "    ---  "0..*"  publication

@enduml